#!/usr/bin/env python

def build(ctx):
    lang = ['c', 'cpp']
    if not ctx.env.DISABLE_JAVA:
        lang += ['java']
    ctx.zcmgen(name    = 'testzcmtypes',
               source  = ctx.path.ant_glob('*.zcm'),
               lang    = lang,
               javapkg = 'test.zcmtypes')
